### ISSUE TITLE
Examples of binding/queue/exchanges/publish

### ISSUE THREAD

**Issue by molinto** [jakobloekke/jakobloekke-rabbitmq#3]
Perhaps add some examples of how to use these in the README if you get time please.

Very different from https://github.com/squaremo/amqp.node

Thanks

**Comment by molinto** [comment]
Can you publish at all from this?
Seems to be just consuming only.

**Comment by jakobloekke** [comment]
This package is a wrapper around https://github.com/postwait/node-amqp. I will update the readme to make that clearer.

It has a different API than amqp.node, so I can see why that would be confusing. :)

**Comment by molinto** [comment]
Thank you for getting back to me :)

**Comment by jakobloekke** [comment]
As for publishing, you do that on an exchange after having declared it:

    RabbitMQ.exchanges.MyExchangeName.publish('key', message_object);

**Comment by molinto** [comment]
Sorry to sounds dumb, but where do I decalre it please:

```
var options = {
            host: 'hare.rmq.cloudamqp.com',
            login: 'ABC',
            password: 'PASS',
            vhost: 'ABCD'
        };

        RabbitMQ.ensureConnection(options);

        var newContact = {
            email: "sharry@email.com"
        };

        var msg = JSON.stringify(newContact);

        RabbitMQ.on('ready', function () {
            RabbitMQ.connection.exchange('amq.topic', {type: 'topic'}, function (exchange) {
                RabbitMQ.exchanges.ExchangeName = exchange;
                RabbitMQ.emit('ExchangeNameHere');
            });
        });

        RabbitMQ.on('ExchangeNameHere', function () {
            RabbitMQ.exchanges.MyExchangeName.publish('contacts.add', new Buffer(msg));
        });

        RabbitMQ.on('error', function (err) {
            console.log(err);
        });

```

Keep getting these errors:
```
[TypeError: Cannot call method 'publish' of undefined]
```

**Comment by jakobloekke** [comment]
In your code above, the exchange is called 'ExchangeName', so you need to change this line:

    RabbitMQ.exchanges.MyExchangeName.publish('contacts.add', new Buffer(msg));

to:

    RabbitMQ.exchanges.ExchangeName.publish('contacts.add', new Buffer(msg));

**Comment by molinto** [comment]
Oh man, didn't see that.
Works perfectly, mucho appreciated.

**Comment by molinto** [comment]
What does this part do please?
RabbitMQ.emit('ExchangeNameHere');

**Comment by jakobloekke** [comment]
Hey! 

It is amazing what one can  invent!  You're  gonna love  it, I swear! Read more here <http://phefubupu.lvbeverage.net/e4wcbbm>

Looking forward, jakob
